### ISSUE TITLE
Проблема с прорисовкой

### ISSUE THREAD

**Issue by EvgenyDanov** [AlexGyver/alexgyver.github.io#12]
когда я запускаю прорисовку изображения, у меня происходит баг 
![image](https://user-images.githubusercontent.com/123499933/227085427-05ebe128-84f3-447f-b034-a9324a086f8e.png)

**Comment by cybernetlab** [comment]
+1 - та же история - трейсится небольшая овальная область в верхнем левом углу вместо всего изображения

**Comment by GyverLibs** [comment]
Какой браузер?

**Comment by cybernetlab** [comment]
Нашёл: https://p5js.org/reference/#/p5/pixels
<img width="736" alt="image" src="https://user-images.githubusercontent.com/1825009/227158508-313998ba-f7dd-462d-b0a2-77f9d648542d.png">

для маков по-другому считается индекс в массиве pixels. У себя уже пофиксил - сейчас PR сделаю

**Comment by GyverLibs** [comment]
Так и знал что это мак)

**Comment by cybernetlab** [comment]
@GyverLibs https://github.com/AlexGyver/alexgyver.github.io/pull/13

**Comment by cybernetlab** [comment]
только надо проверить на не-маках )

**Comment by cybernetlab** [comment]
@GyverLibs  да - ещё поменял `i` на `idx` - у тебя в `clearLine` `i` во внешнем цикле используется

**Comment by copych** [comment]
Это не только маков касается, у меня на винде так же было. Это viewport scaled meta-pixels, я сделал pull request с фиксом.

**Comment by GyverLibs** [comment]
Блин, получается у нас есть два разных решения проблемы маков. Может посмотрите варианты друг друга и выберем один?

**Comment by cybernetlab** [comment]
> Это не только маков касается, у меня на винде так же было. Это viewport scaled meta-pixels, я сделал pull request с фиксом.

имхо всё таки лучше пользоваться наливной функцией из библиотеки `p5` - `pixelDensity`. Только надо проверить, что на винде (конкретно в твоём случае) она также верное значение даёт

**Comment by cybernetlab** [comment]
@copych посмотрел исходники `p5` - они используют `window.devicePixelRatio` для установки правильного density (https://github.com/processing/p5.js/blob/main/src/core/main.js#L172). Можешь у себя в браузере посмотреть, что выдаёт `window.devicePixelRatio`? Если `> 1`, то можно моё решение использовать - оно будет работать

**Comment by AlexGyver** [comment]
на винде выдаёт 1

**Comment by cybernetlab** [comment]
@AlexGyver у тебя и должна выдавать 1. больше единице должно быть у @copych

**Comment by AlexGyver** [comment]
я запушил, из PR взял частично руками

**Comment by copych** [comment]
@cybernetlab у меня в main.js 0.6666666865348816 выдало.
Вылечилось вот так:
```
    cbox= select('meta[name=viewport]');
    cbox.attribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0');
```
в setup() сразу после  createCanvas(ui_offs + cv_d * 2 + 50 * 3, cv_d + 100);
посмотри, на маке помогает?

**Comment by cybernetlab** [comment]
@AlexGyver подготовил ПР с контролем радиального заполнения точек - подробности в комменте к ПР: https://github.com/AlexGyver/alexgyver.github.io/pull/16

**Comment by cybernetlab** [comment]
@copych ща стяну свежий мастер, проверю

**Comment by AlexGyver** [comment]
там продублировалась density у тебя

**Comment by AlexGyver** [comment]
маководы, просьба проверить текущую версию, работает?

**Comment by cybernetlab** [comment]
> @cybernetlab у меня в main.js 0.6666666865348816 выдало. Вылечилось вот так:
> 
> ```
>     cbox= select('meta[name=viewport]');
>     cbox.attribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0');
> ```
> 
> в setup() сразу после createCanvas(ui_offs + cv_d * 2 + 50 * 3, cv_d + 100); посмотри, на маке помогает?

@copych  к сожалению (( На маке этот финт не проходит - ровно такой же результат. Попробуй наоборот теперь ты моё решение - стяни мой ПР: https://github.com/AlexGyver/alexgyver.github.io/pull/13

**Comment by copych** [comment]
@cybernetlab у меня твой фикс работает

**Comment by cybernetlab** [comment]
огонь

**Comment by cybernetlab** [comment]
из моего фикса main.js, остальное от @copych и ещё в main.js надо деление на длину - так намного лучше

**Comment by AlexGyver** [comment]
@copych проверь мастер версию плиз)

**Comment by copych** [comment]
@AlexGyver у меня работает, только приходится масштаб 75% ставить в браузере, иначе все не влезает

**Comment by copych** [comment]
> 
как я вижу, уже не влияет, можно вынести
