### ISSUE TITLE
Нить никогда не возвращается в один из колышков(похоже нулевой)

### ISSUE THREAD

**Issue by alfedukovich** [AlexGyver/alexgyver.github.io#27]
![изображение](https://user-images.githubusercontent.com/8695578/227708391-8ad6255f-0ced-4bea-94b6-7559c4ec46f8.png)

**Comment by AlexGyver** [comment]
Ох блин точно, спасибо! Остался с каких то времён этот костыль
![image](https://user-images.githubusercontent.com/21090953/227708690-278a5210-8b66-43bb-a7f9-ad07ef14626e.png)
